### ISSUE TITLE
WP error when logging out

### ISSUE THREAD

**Issue by alexeightsix** [tadpolecc/civi_member_sync#23]
I'm receiving this error when I logout:

Fatal error: Call to a member function has_cap() on a non-object in /srv/www/default/wp-content/plugins/civi_member_sync-master/civi_member_sync.php on line 127

I'm using latest WP

**Comment by kcristiano** [comment]
Thanks @alexeightsix What version of CiviCRM?

I will look at this when I get a chance, but for version 4.6 and above of CiviCRM I am using https://github.com/christianwach/civicrm-wp-member-sync   

The new plugin is based on this one, but much improved as this was a simple fix up of an old broken plugin.

If you are on 4.6 of CiviCRM, I suggest you switch over to @christianwach's plugin.
